spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boardtest?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: jehyun1590~!


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update

      properties:
        hibernate:
          format_sql: true
